name: Deploy Javadocs to GitHub Pages

on:
  push:
    branches:
      - main
      - it-0
      - it-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar el repositorio y obtener el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Instalar sdkman y Java
      - name: Install SDKMAN! and Java
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 22.0.1-open
          echo "JAVA_HOME=$(sdk home java 22.0.1-open)" >> $GITHUB_ENV

      # Paso 3: Dar permisos ejecutables a gradlew
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Paso 4: Construir los Javadocs
      - name: Generate Javadocs
        run: ./gradlew javadoc

      # Paso 5: Publicar los Javadocs en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/docs/javadoc # Directorio donde se generan los Javadocs
          publish_branch: gh-pages # Especifica la rama de despliegue
